import {loadData,staking} from './data-layer.js?v=5';
import {generateTicket,sportGroup} from './ticket.js?v=2';
'use strict';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=x=>x==null?'—':(100*x).toFixed(1)+'%',num=x=>x==null?'—':x.toFixed(2),signed=x=>x==null?'—':(x>=0?'+':'')+num(x);
let data;let lastTicket=null;const storedBankroll=Number(localStorage.getItem('prono-bankroll')??500);$('bankroll').value=Number.isFinite(storedBankroll)&&storedBankroll>=0&&storedBankroll<=1000000?storedBankroll:500;const bankroll=()=>{const v=Number($('bankroll').value);return Number.isFinite(v)&&v>=0&&v<=1000000?v:0;};$('bankroll').addEventListener('input',()=>{if(!$('bankroll').value||!$('bankroll').checkValidity())return;localStorage.setItem('prono-bankroll',$('bankroll').value);render();renderTicketStake();});const day=(iso,zone)=>new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(iso));
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(n=>n.classList.toggle('active',n===b));}));
$('zone').value=localStorage.getItem('prono-zone')||'Europe/Rome';$('zone').addEventListener('change',()=>{localStorage.setItem('prono-zone',$('zone').value);render();});$('league').addEventListener('change',render);$('sport').addEventListener('change',()=>{$('league').value='';render();});
const time=p=>new Date(p.kickoff).toLocaleTimeString('it-IT',{timeZone:$('zone').value,hour:'2-digit',minute:'2-digit'});
function card(title,n,content,band){return `<article class="card"><div class="top"><span class="eyebrow">${title}</span><span class="number">${n}</span></div>${content}<div class="band">${band}</div></article>`;}
function picked(p){return `<h3>${esc(p.home)}<br>${esc(p.away)}</h3><div>${esc(p.outcome)} · ${esc(p.league)} · ${time(p)}</div><div class="odds">${num(p.market.odds)}</div><p class="empty">Modello ${pct(p.model)} · Mercato ${pct(p.market.p)}<br>Confidence ${Math.round(p.analysis.confidence)}/100 · ${esc(p.market.book)}</p>${stakeHTML(p)}`;}
function render(){if(!data)return;const zone=$('zone').value,now=new Date(),today=day(now,zone),stale=day(data.generatedAt,zone)!==today;
  $('date').textContent=now.toLocaleDateString('it-IT',{timeZone:zone,weekday:'long',day:'numeric',month:'long'});
  $('fresh').textContent=(stale?'Dati da aggiornare':'Snapshot verificato')+' · '+new Date(data.generatedAt).toLocaleTimeString('it-IT',{timeZone:zone,hour:'2-digit',minute:'2-digit'});
  $('notice').className='notice'+(stale?' warn':'');$('notice').textContent=stale?'Lo snapshot disponibile non è di oggi. Le selezioni sono sospese in attesa del prossimo aggiornamento.':`Dati del ${new Date(data.generatedAt).toLocaleString('it-IT',{timeZone:zone})}. Le quote possono cambiare. Confidence e probabilità sono due misure diverse.`;
  if(Object.values(data.report.marketComparison.bootstrap).every(x=>x.ci95[0]>0))$('notice').textContent+=' Nel backtest il modello è risultato peggiore del closing: nessun vantaggio sul mercato dimostrato.';
  const pool=data.sourceMode==='fallback'?data.picks:stale?[]:data.picks.filter(p=>day(p.kickoff,zone)===today&&new Date(p.kickoff)>now);
  $('data-mode').textContent=data.sourceMode==='fallback'?'Modalità esempi reali archiviati · '+new Date(data.generatedAt).toLocaleString('it-IT')+' · Stake operativi disabilitati.':'Snapshot online · stake ricalcolati sul bankroll inserito.';
  if(data.sourceMode==='fallback'){$('fresh').textContent='Esempi reali archiviati';$('notice').textContent='Il feed principale non è disponibile. Stai consultando dati reali archiviati del '+new Date(data.generatedAt).toLocaleString('it-IT')+'. Quote non attuali, stake operativi sospesi.';$('notice').className='notice warn';}
  const lookup=id=>data.sourceMode==='fallback'?null:pool.find(p=>p.id===id);const single=lookup(data.selections.single),high=lookup(data.selections.high),combo=data.selections.combo;
  const empty='<h3>Nessuna selezione.</h3><p class="empty">Nessun evento disponibile supera tutti i filtri di quota, valore e qualità.<br>Oggi, anche aspettare è una scelta.</p>';
  let combined=empty;if(combo&&combo.legs.every(lookup))combined=`<h3>${combo.legs.length} partite, una combinata</h3><p>${combo.legs.map(id=>{const p=lookup(id);return `${esc(p.home)} – ${esc(p.away)} · ${p.outcome}`;}).join('<br>')}</p><div class="odds">${num(combo.odds)}</div><p class="empty">P congiunta stimata ${pct(combo.probability)} · ${esc(combo.book)}<br>Indipendenza fra partite approssimata.</p>`;
  $('selections').innerHTML=card('SINGOLA PRUDENTE','01',single?picked(single):empty,'BANDA QUOTA 1.50 — 1.85')+card('COMBINATA','02',combined,'2–3 PARTITE · QUOTA 1.85 — 2.50')+card('AD ALTA QUOTA','03',high?picked(high):empty,'BANDA QUOTA 2.50 — 5.00 · PIÙ VARIANZA');
  const grouped=new Map();for(const p of pool.filter(p=>($('sport').value==='all'||sportGroup(p)===$('sport').value)&&(!$('league').value||p.league===$('league').value))){if(!grouped.has(p.eventId))grouped.set(p.eventId,[]);grouped.get(p.eventId).push(p);}
  $('matches').innerHTML=[...grouped.values()].map(rows=>{const p=rows[0];return `<article class="fixture"><div class="fixture-head"><strong>${esc(p.home)} <span style="color:#9ba593">—</span> ${esc(p.away)}</strong><small>${esc(p.league)} · ${time(p)}</small></div>${p.quant?.homeXG!=null?'<div class="why">xG attesi '+num(p.quant.homeXG)+' – '+num(p.quant.awayXG)+' · Over 2,5 '+pct(p.quant.markets.over25)+' · Goal '+pct(p.quant.markets.goal)+' (nessuna quota disponibile per questi mercati)</div>':''}${p.model===null?'<div class="why">Nessun modello indipendente · solo consenso di mercato</div>':''}<div class="table-scroll"><table><thead><tr><th>Esito</th><th>Modello</th><th>Mercato</th><th>Quota equa</th><th>Disponibile</th><th>Edge / EV</th><th>Confidence</th><th>EV+ / Kelly 25%</th><th>Classe</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.outcome)}</strong></td><td><strong>${pct(r.model)}</strong></td><td>${pct(r.market.p)}<br><small>${r.market.n} book</small></td><td>${num(r.analysis?.fair)}</td><td><strong>${num(r.market.odds)}</strong><br><small>${esc(r.market.book)}</small></td><td>${r.analysis?pct(r.analysis.edge)+' / '+pct(r.analysis.ev):'—'}</td><td>${r.analysis?Math.round(r.analysis.confidence)+'/100<span class="bar"><i style="width:'+Math.round(r.analysis.confidence)+'%"></i></span>':'—'}</td><td>${stakeHTML(r)}</td><td><span class="pill ${r.analysis?.category.startsWith('VALORE')?'value':r.analysis?.category==='DA OSSERVARE'?'watch':''}">${esc(r.analysis?.category||r.marketQuality)}</span></td></tr>`).join('')}</tbody></table></div><details class="why"><summary>Perché queste probabilità</summary>${rows.map(r=>`<p><strong>${r.outcome}.</strong> ${esc(r.quantStatus||'')} · ${esc(r.why)} ${r.movement?'Variazione osservata: '+r.movement.books.map(b=>esc(b.book)+' '+num(b.from)+' → '+num(b.to)).join('; '):'Variazioni quota: seconda osservazione comparabile non disponibile.'}</p>`).join('')}</details></article>`;}).join('')||'<div class="zero">Nessuna partita con dati sufficienti nei filtri attuali.</div>';
  $('sources').innerHTML='<p>Calcio: '+pool.filter(p=>sportGroup(p)==='calcio').length+' esiti · Tennis: '+pool.filter(p=>sportGroup(p)==='tennis').length+' esiti · Basket: '+pool.filter(p=>sportGroup(p)==='basket').length+' esiti. Zero indica assenza di eventi o di quote sufficienti nello snapshot.</p>'+data.coverage.map(c=>`<p><strong>${esc(c.league)}</strong> · ${c.matches} partite xG · ultima partita ${esc(c.lastMatch.slice(0,10))}</p>`).join('');$('diagnostics').innerHTML=data.diagnostics.map(x=>'<li>'+esc(x)+'</li>').join('');
  const r=data.report;$('backtest').innerHTML=`<h2 style="margin:30px 0 15px">Validazione pubblica</h2><p class="notice warn">${esc(r.limitations[1])}</p><p>${esc(r.method)}</p><div class="table-scroll box"><table><thead><tr><th>Split</th><th>Partite</th><th>Brier ↓</th><th>Log loss ↓</th><th>RPS ↓</th></tr></thead><tbody>${Object.entries(r.splits).map(([k,v])=>`<tr><td>${k}</td><td>${v.n}</td><td>${v.brier.toFixed(4)}</td><td>${v.logLoss.toFixed(4)}</td><td>${v.rps.toFixed(4)}</td></tr>`).join('')}</tbody></table></div><h3>Confronto con il closing storico</h3><p>Bootstrap appaiato per blocchi settimanali · 3.000 repliche · differenza modello − mercato. Valori positivi indicano un risultato peggiore del modello.</p><div class="table-scroll box"><table><thead><tr><th>Metrica</th><th>Differenza</th><th>Intervallo 95%</th></tr></thead><tbody>${Object.entries(r.marketComparison.bootstrap).map(([k,v])=>`<tr><td>${k}</td><td>${v.difference.toFixed(4)}</td><td>[${v.ci95.map(x=>x.toFixed(4)).join('; ')}]</td></tr>`).join('')}</tbody></table></div><p class="notice">${esc(r.improvements.decision)}</p><ul>${r.limitations.filter((_,i)=>i!==1).map(x=>'<li>'+esc(x)+'</li>').join('')}</ul>`;
  const c=data.clvSummary;$('clv-metrics').textContent=c?'CLV medio: '+pct(c.mean)+' · '+c.closed+' osservazioni chiuse / '+c.tracked+' segnalazioni · '+c.pending+' in attesa · '+c.missing+' senza closing valido.':'Nessuna osservazione CLV ancora disponibile.';
  $('limits').innerHTML=data.limits.map(x=>'<li>'+esc(x)+'</li>').join('');
  $('performance').innerHTML=Object.keys(data.performance).length?`<div class="table-scroll box"><table><thead><tr><th>Categoria</th><th>Chiusi</th><th>Saldo quote osservate</th><th>Saldo teorico quote eque</th></tr></thead><tbody>${Object.entries(data.performance).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${v.n}</td><td>${signed(v.pnl)} u.</td><td>${signed(v.fairPnl)} u.</td></tr>`).join('')}</tbody></table></div>`:'<div class="zero">Nessun pronostico del nuovo registro è ancora chiuso. Nessun rendimento da mostrare.</div>';
  $('history-rows').innerHTML=`<p>${data.pendingOld} pronostici attendono un risultato da oltre 3 giorni. Lo storico precedente è conservato, ma escluso da questi conteggi perché non interamente verificabile.</p>`+data.history.slice().reverse().map(p=>`<p>${esc(p.home)} – ${esc(p.away)} · ${p.outcome} · ${esc(p.result)} · ${signed(p.pnl)} u.</p>`).join('');
}
loadData().then(d=>{if(d.schema!==2)throw Error('Formato non supportato');data=d;const books=new Map(d.picks.flatMap(p=>p.market.prices.map(b=>[b.key,b.title])));for(const [key,title] of books){const o=document.createElement('option');o.value=key;o.textContent=title;$('ticket-book').append(o);}for(const league of [...new Set(d.picks.map(p=>p.league))]){const option=document.createElement('option');option.value=league;option.textContent=league;$('league').append(option);}render();}).catch(()=>{$('fresh').textContent='Dati non disponibili';$('notice').className='notice warn';$('notice').textContent='Impossibile verificare i dati pubblicati. Riprova più tardi: nessuna selezione viene mostrata.';});
setInterval(()=>{if(data){render();$('ticket-result').innerHTML='<p>Rigenera la multipla per verificare orari e freschezza delle quote.</p>';}},60000);

$('ticket-form').addEventListener('submit',e=>{e.preventDefault();if(!data)return;if(data.sourceMode==='fallback'){$('ticket-result').textContent='Esempi archiviati: generazione di giocate operative disabilitata.';return;}try{const r=generateTicket(data.picks,{target:Number($('target').value),stake:Number($('stake').value),maxLegs:Number($('legs').value),tolerance:Number($('tolerance').value),sport:$('ticket-sport').value,mode:$('ticket-mode').value,book:$('ticket-book').value,zone:$('zone').value});const t=r.ticket||r.nearest;lastTicket=t;$('ticket-result').innerHTML=(r.ticket?'<h3>Multipla nella fascia richiesta</h3>':'<h3>Nessuna multipla nella fascia richiesta</h3>')+'<p>Intervallo '+num(r.low)+' – '+num(r.high)+'. '+r.eligible+' esiti disponibili.</p>'+(t?'<p>'+(r.ticket?'':'Alternativa più vicina trovata, fuori obiettivo: ')+'<strong>Quota '+num(t.odds)+'</strong> · '+esc(t.bookTitle)+'</p><ol>'+t.legs.map(p=>'<li>'+esc(p.home)+' – '+esc(p.away)+' · '+esc(p.outcome)+' @ '+num(p.ticketOdds)+'</li>').join('')+'</ol><p>Puntata '+num(t.stake)+' € · ritorno lordo se vincente '+num(t.gross)+' € · utile '+num(t.net)+' €.</p><p>Probabilità congiunta mercato '+pct(t.marketP)+' · modello '+pct(t.modelP)+'. Indipendenza fra eventi approssimata. Quote da riconfermare presso il bookmaker.</p>':'<p>Prova un altro sport o attendi nuove quote: non vengono inventate combinazioni.</p>')+(r.truncated?'<p>Limite di ricerca raggiunto: il risultato è il migliore fra le combinazioni esaminate.</p>':'');;$('ticket-result').insertAdjacentHTML('beforeend','<div id="ticket-kelly"></div>');renderTicketStake();}catch{$('ticket-result').textContent='Controlla quota e importo inseriti.';}});

function stakeHTML(p){const v=staking(p,bankroll(),{fallback:data?.sourceMode==='fallback'});if(!v)return '<span>Modello non disponibile</span><br><small>Stake non calcolabile</small>';return (v.qualifies?'<span class="ev-badge">EV+ '+pct(v.ev)+'</span>':'<span>EV '+pct(v.ev)+'</span>')+'<p class="stake"><strong>Stake consigliato (Kelly 25%)</strong><br>'+pct(v.suggestedFraction)+' del bankroll · '+num(v.suggestedStake)+' €</p>'+(!v.actionable?'<small>Dati storici o quote scadute: stake sospeso.</small>':!v.qualifies?'<small>Sotto la soglia EV +3%.</small>':'');}
function renderTicketStake(){if(!$('ticket-kelly')||!lastTicket)return;const t=lastTicket;$('ticket-kelly').innerHTML=t.modelP===null?'<p>Kelly della multipla non calcolabile: manca un modello per almeno un esito.</p>':stakeHTML({model:t.modelP,kickoff:t.legs.map(p=>p.kickoff).sort()[0],generatedAt:t.legs[0].generatedAt,market:{p:t.marketP,odds:t.odds,age:Math.max(...t.legs.map(p=>p.market.age))}})+'<small>Probabilità congiunta ottenuta assumendo indipendenza fra eventi.</small>'; }
