import {finite,timestamp} from './math.mjs';
export function closingLineValue(entry,closing){finite(entry,'entry',1.000001);finite(closing,'closing',1.000001);return entry/closing-1;}
export function registerValueEntries(records,picks){const out=structuredClone(records),ids=new Set(out.map(r=>r.id));for(const p of picks){if(!Number.isFinite(p.model)||p.model*p.market.odds-1<.03-1e-12)continue;const book=p.market.prices.find(b=>b.title===p.market.book&&b.odds===p.market.odds);if(!book)continue;const id=[p.id,book.key,p.version].join('|');if(ids.has(id))continue;if(timestamp(p.generatedAt)>=timestamp(p.kickoff))continue;out.push({id,eventId:p.eventId,sport:p.sport,home:p.home,away:p.away,kickoff:p.kickoff,market:'h2h',outcome:p.outcome,book:book.key,bookTitle:book.title,entryAt:p.generatedAt,entryOdds:book.odds,modelProbability:p.model,modelVersion:p.version,status:'pending',closingOdds:null,closingAt:null,clv:null});ids.add(id);}return out;}
export function observeClosing(records,events,observedAt,{windowMinutes=20}={}){timestamp(observedAt);finite(windowMinutes,'finestra',1,60);return records.map(original=>{const r={...original};if(r.status!=='pending')return r;const start=timestamp(r.kickoff),now=timestamp(observedAt);if(now>=start){r.status=r.closingOdds===null?'missing':'closed';if(r.closingOdds!==null)r.clv=closingLineValue(r.entryOdds,r.closingOdds);return r;}if(start-now>windowMinutes*60000)return r;
 const e=events.find(e=>e.id===r.eventId&&e.home_team===r.home&&e.away_team===r.away&&timestamp(e.commence_time)===start);if(!e)return r;
 const b=e.bookmakers?.find(b=>b.key===r.book),m=b?.markets?.find(m=>m.key===r.market);if(!m)return r;
 const name=r.outcome==='1'?r.home:r.outcome==='2'?r.away:'Draw',o=m.outcomes?.find(o=>o.name===name);if(!o||!Number.isFinite(o.price)||o.price<=1)return r;
 const updated=m.last_update||b.last_update;let t;try{t=timestamp(updated);}catch{return r;}
 if(t>=start||t>now||t<=timestamp(r.entryAt)||start-t>windowMinutes*60000||now-t>10*60000||r.closingAt&&t<=timestamp(r.closingAt))return r;
 r.closingOdds=o.price;r.closingAt=updated;r.observedAt=observedAt;return r;});}
export function clvSummary(records){const closed=records.filter(r=>r.status==='closed'&&Number.isFinite(r.clv));return {tracked:records.length,closed:closed.length,pending:records.filter(r=>r.status==='pending').length,missing:records.filter(r=>r.status==='missing').length,mean:closed.length?closed.reduce((s,r)=>s+r.clv,0)/closed.length:null,definition:'Entry / ultima quota osservata dello stesso bookmaker nei 20 minuti prima del via − 1. Media per segnalazione, non prova di profitto.'};}
